keys:
  - &users:
    - &shreyd age1u68x5c2333cpz43ewpt3z4m2pp6v2rv4e0fy0p6qkzf4rlmnrftsayhywf
  - &hosts:
    - &neo16 age1t2xf2u2c9jlkxugflrmk50kdnctt47q95cs3krgsvq4au7amtg8skzzvrq
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *shreyd
        - *neo16
